# Generated by Django 5.0.6 on 2024-06-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='guestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='firstName')),
                ('lastName', models.CharField(max_length=50, verbose_name='lastName')),
                ('guestPassword', models.CharField(max_length=128, verbose_name='guestPassword')),
            ],
        ),
    ]
