# Generated by Django 5.0.6 on 2024-06-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_guestuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestuser',
            name='guestPassword',
        ),
        migrations.AddField(
            model_name='guestuser',
            name='guestUserName',
            field=models.CharField(default='nullUser', max_length=50, verbose_name='guestUserName'),
        ),
    ]
