# Generated by Django 5.0.6 on 2024-06-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isGuest',
            field=models.BooleanField(default=True),
        ),
    ]
